services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
    env_file:
      - .env
    ports:
      - 3000:3000
  postgres:
    image: postgres:latest
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - bookdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U prerecover -d prerecover"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    networks:
      - postgres

  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - ".env"
    environment:
      PGADMIN_DEFAULT_EMAIL: "bookdb@book.com"
      PGADMIN_DEFAULT_PASSWORD: ${POSTGRES_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 600M
    networks:
      - postgres
volumes:
  bookdata:
  pgadmin-data:
networks:
  postgres:
    driver: bridge
